### ISSUE TITLE
Error when scanning

### ISSUE THREAD

**Issue by popouille** [X-Ryl669/kutr#11]
Hello,

I tru to scan my media directory, but nothing append, in my logs i have:

> production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Cannot access protected property App\Models\File::$song in /var/www/vhosts/***/httpdocs/***/app/Services/Media.php:178

**Comment by popouille** [comment]
I got it working by using 

> php artisan koel:sync --force

 Instead of scanning from web interface.

koe:sync command returned me this error:

> Integrity` constraint violation: 1048 Column 'disc' cannot be null

then in phpmyadmin "Songs" table structure, i checked "Null" for the "Disc" column

Then i run again: php artisan koel:sync --force

And now it works

Edit:

But songs don't play, i have all my directories i click on play a directory, and nothing append

**Comment by X-Ryl669** [comment]
Thanks, I'll take a look since "disc" column was added first in kutr then later in koel, yet Laravel db handling is a real mess when dealing with a fork and a db.

When browsing folders, you have 2 buttons. The orange one "this" only plays song present in the selected folder (not its subfolders). The green one "all" plays all songs recursively.
If you don't have song in the current folder (because it's a top level folder, then clicking "this" does not do anything)

**Comment by baumschubser** [comment]
Any news on this? I have the same problem. 

When I make the column "disc" nullable, `php artisan koel:sync` works, but no songs are listed (but the folders of synced songs are listed in folder view - empty). 

In laravel.log, I see the following error:
`production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Cannot access protected property App\Models\File::$song in /srv/kutr/app/Services/Media.php:178`

When I set the property to public (app/Models/File.php, Line 57), this error pops up in laravel.log:
`production.ERROR: BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::getArtistAttribute() in /srv/kutr/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2445`

…and this is true, too - there is no such method. @X-Ryl669, any idea how to proceed? Kutr really is a significant improvement for me (loginRedir allows for running it behing HTTP basic auth and folder view is the best - I would love to use this!).

**Comment by X-Ryl669** [comment]
Please try the last commit and let me know if it's working for you.
The reported error should not prevent inserting songs in database on the command line, so I'm almost sure there is another issue than reported here.
Your `disc` column should not be nullable. My table declaration is like this:
```
CREATE TABLE `songs` (
  `id` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `album_id` int(10) unsigned NOT NULL,
  `artist_id` int(10) unsigned DEFAULT NULL,
  `genre_id` int(10) unsigned NOT NULL DEFAULT '1',
  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `length` double(8,2) NOT NULL,
  `track` int(11) DEFAULT NULL,
  `disc` int(11) NOT NULL DEFAULT '1',
  `lyrics` text COLLATE utf8_unicode_ci NOT NULL,
  `path` text COLLATE utf8_unicode_ci NOT NULL,
  `mtime` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `songs_album_id_foreign` (`album_id`),
  KEY `songs_contributing_artist_id_foreign` (`artist_id`),
  KEY `songs_genre_id_foreign` (`genre_id`),
  CONSTRAINT `songs_album_id_foreign` FOREIGN KEY (`album_id`) REFERENCES `albums` (`id`),
  CONSTRAINT `songs_genre_id_foreign` FOREIGN KEY (`genre_id`) REFERENCES `genres` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

**Comment by baumschubser** [comment]
Thank you! The commit solved indeed my issue. Of course [new problems arise](https://stackoverflow.com/questions/53697003/laravel-app-with-basic-auth-in-url-ok-for-web-not-ok-for-api) but that's another story.
