### ISSUE TITLE
details on cms

### ISSUE THREAD

**Issue by Fahad-pnw** [X-Ryl669/kutr#2]
Hi, 

I love your work on koel, i wonder if you have managed to successfully integrate the whole thing with some cms, i'd really like your input on that, if we can discuss a few things or you could talk a while? if too busy, can you please guide what did you integrate with kutr for cms? a laravel, custom built cms? or could there be something that'd speed up all the development?

beside, if you d share out your cms code, that would be like awesome! if not, if you can just guide a few things, that would be amazing!

**Comment by X-Ryl669** [comment]
Yes, I've integrated Kutr with my (own) CMS. Using any other CMS should be possible, provided you keep this:

1. Kutr must run with its own subdomain (this is a restriction with Laravel, and I have not removed it)
2. You have access to the source code for your CMS and the API for login and logout are documented

Then, in that case, you'll have to do so (I'm going to copy this in a wiki page):

1. Copy the file `cms_login.php.example` to `cms_login.php` in the root dir of your CMS.
2. If you look into that file, you'll find it's structured in 3 parts, authenticating with your CMS, making a token and redirecting to Kutr.

The first part, if specific to your CMS. That's the lines:
```
// Require your CMS bootstrap code here
require_once("yourCMSbootstrap.php");
// Bootstrap your CMS and check the session is valid (if not your CMS will fallback the login screen)
checkSession();

// The basic idea being to match the user name in your CMS with the user name in Kotr's DB, you must have 1:1 user name in both
$login = getCurrentUserLogin();
```
Usually, the `require_once` is explained in the documentation of your CMS in the section "bootstrapping". Typically, this calls the class autoloader, and all the other stuff required for your CMS basic functions to work.

The function `checkSession()` is valid for my CMS, but you'll need to adapt to yours. Typically, this is where the CMS checks the session (cookie, token, whatever) for the current user is valid, and if not redirect to the login page.

The function `getCurrentUserLogin()` must return the name of the current user logged-in. You **must** have a 1:1 mapping between this name in your CMS and the account's name in Kutr.

That's for the first part.

Then, the second part is not that hard:
```
// Should be the same as the one set in .env file in the REMOTE_AUTH_SECRET key
$secret = "<your secret here>";
```
The comment says it all, you'll need to write here the secret you've chose (whatever you want, but must be the same in both this file and the content of the `REMOTE_AUTH_SECRET` variable in your `.env` file.

The last part you need to modify is the redirection URL:
```
header("Location: ".$https."music.yourserver.net/loginRedir.php?token=".makeToken());
```
Obviously, you need to change "music.yourserver.net" to the subdomain of the Kutr's installation.


When you've done this, you're 99% done, you just need to add a link in your CMS to this file, that is, you need to add somewhere in your CMS's rendered output a `<a href='cms_login.php'>Music</a>` and you're done, it should work for login.

Logout is even simpler, you need to figure out what is the logout URL for your CMS, and write this URL in the `.env` file.

**Comment by Fahad-pnw** [comment]
thank you so much for your detailed response.

again, i dont think you mean to share the cms here, or could you help me with what you've done already? would ease a lot of things for me. if you can, can we talk abt this on email fahad@penandweb.com

**Comment by X-Ryl669** [comment]
I'm not sharing my CMS, that does not make any sense here. 
Please try to follow the instructions I've posted above and if it does not work, report here so I can improve my code (or documentation). I don't intend to support every CMS on the Internet (not enough time), and to be honest, some development competencies are required to make the glue code for a new CMS since you must learn to develop with the CMS's API.

If you have time to explain what's wrong with your CMS, and the steps you've made to get it to work, I'll add your experience in the Wiki so it might help other (or better, add a `cms_yourCMS.php.example` file in the repository like I did for `cms_login.php`)
