### ISSUE TITLE
Song->multiple albums? 

### ISSUE THREAD

**Issue by Fahad-pnw** [X-Ryl669/kutr#3]
Hi can you help me through the following in figuring out a solution. 

I have been looking to find a solution to add a single entry of song to multiple albums? I have looked through various details, like within the issues, there's conpilations. So basically, this might do that?

Looking into the database, i cant really say if it does how i would like it to work. Apparently, a single song could belong to multiple albums, so it's a one to many relation, yet i dont really that as an option.

Can anyone pls suggest if this is currently possible or would i need to go into the details and customize it for myself?

The way i see it, if the song path is duplicated and a new entity is made for each song that has to belong to another album, only a new id would need to be alloted but this doesn't really look like a good option.

The way this is currently established, i think this would be the fastest way around. Any suggestions on how i can do this? Put a single song in multiple albums?

**Comment by X-Ryl669** [comment]
With this version of the repository, you can't do it directly (or it'll be complex).
Typically, here's the closest to what you want:

1. You must organize your music libraries in folders with folders as album
2. You should have a symbolic link for the song you want to share between albums (so there's only one song stored on your drive, but as many links as you want songs in the end)
3. In each album (hence folder) where you have such "dual head" songs, you must create a .virtual-album file (the file could be empty, **Kutr** just check for its presence). Then, the `album` tag will be replaced by the folder name.

Currently, you can't have the same song under different artist.

**Comment by Fahad-pnw** [comment]
thanks for your awesome reply, seems like i'd make this happen this way!

again, i've another question, would i be requiring another table to publicize a playlist? let's say i want to create a favorites that are my favorites but are shared to all, publicly? or rather, if i need a curated-playlist (multiple) and want it be linked to a submenu? i'd like to know what your approach would be to this. I'm quite new to vue and this being the first project, its quite messing up my head.

would love your suggestions on making 'curated playlists' or to define it easier, 'a playlist that can be seen by all users' again, should i need to prepare a separate table for this or should i simply look forward into ways i'd make any playlist sharable, say with a boolean set on playlist table?

**Comment by X-Ryl669** [comment]
Well, sorry, this can not work. You can't download songs without a valid authentication token. So you can't make a song "public" with **Kutr**. Probably better to use another software for this.
