### ISSUE TITLE
song-item-simple.vue not found

### ISSUE THREAD

**Issue by GaetanNaulin** [X-Ryl669/kutr#4]
Hi,

I tried to install kutr on my ubuntu, but I have an error with gulp : 
> Browserify Failed!: Cannot find module './song-item-simple.vue' from '/home/gat/Code/kutr/resources/assets/js/components/shared'

I checked and this file is not present in the repository, but in /resources/assets/js/components/shared/folder-item.vue I found this : 
` import songItemSimple from './song-item-simple.vue'` : line 46

I like your work on koel/kutr, and I really wish I could install it.
Thanks !

**Comment by X-Ryl669** [comment]
I've made a new commit for the missing file. Please retry.
In the future, I'll try to set up Travis so this will not goes under the radar. Sorry for the missing file.

**Comment by GaetanNaulin** [comment]
Thanks it's works !

But now, on the login page nothing is displayed, the login form has attribute : 
`style="display:none;"`

I don't know vuejs to fix this.. :/

**Comment by X-Ryl669** [comment]
You don't have a CMS, do you ?
In that case, you need to set `const USING_CMS = false;` in `resources/assets/js/app.vue` (and in the .env file too).
See main page for instructions.

**Comment by GaetanNaulin** [comment]
Oh thanks, sorry for my mistake.. It's working !
