### ISSUE TITLE
Tried to install but foreign key errors

### ISSUE THREAD

**Issue by Mattssn111** [X-Ryl669/kutr#7]
I would like to use this, but when I try to install fresh I am getting foreign key errors in the koel:init command, doesn't seem to do that When installing Koel, any advice?

**Comment by X-Ryl669** [comment]
Can you copy the complete error message so I can figure this out ?
As I'm trying to keep synchronized with Koel and because the way the database migration are working in Laravel, I might have missed some database up/downgrade file. So the exact error code will be very useful.

**Comment by coderobe** [comment]
I think these are the error messages @mattssn is referencing:
```
  [Illuminate\Database\QueryException]                                                                                                                                                        
  SQLSTATE[HY000]: General error: 1832 Cannot change column 'genre_id': used in a foreign key constraint 'songs_genre_id_foreign' (SQL: ALTER TABLE songs CHANGE COLUMN genre_id genre_id in  
  t(10) unsigned NOT NULL DEFAULT 1)                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                   
  [Doctrine\DBAL\Driver\PDOException]                                                                                              
  SQLSTATE[HY000]: General error: 1832 Cannot change column 'genre_id': used in a foreign key constraint 'songs_genre_id_foreign'  
                                                                                                               
  [PDOException]                                                                                                                   
  SQLSTATE[HY000]: General error: 1832 Cannot change column 'genre_id': used in a foreign key constraint 'songs_genre_id_foreign'  
```

**Comment by coderobe** [comment]
The offending migration is here: [database/migrations/2017_09_21_112320_ensure_genreid_not_null.php#L20](https://github.com/X-Ryl669/kutr/blob/master/database/migrations/2017_09_21_112320_ensure_genreid_not_null.php#L20)

**Comment by coderobe** [comment]
There's also a missing migration that adds the `is_compilation` column to the `albums` table

**Comment by X-Ryl669** [comment]
Ok, I'll take a look thanks.

**Comment by X-Ryl669** [comment]
Can you try again with the new commit ? 
It should have fixed it.
The `is_compilation` column was dropped in koel's master I'm tracking so I've modified the code referring to that (in the new commit) so it should not be required anymore.

**Comment by X-Ryl669** [comment]
I suppose this is fixed. If not, feel free to re-open.
